### ISSUE TITLE
"Invalid broker address defined" error

### ISSUE THREAD

**Issue by virgilvox** [adafruit/Adafruit_CircuitPython_AWS_IOT#12]
I'm getting this error. I have log set to true, all credentials and secrets parameters are correct, Adafruit PyPortal on version 5 firmware with the latest bundle, esp firmware version 1.6.0. 

I also confirmed the minimqtt and AWS IoT libraries are both at the latest version. I'm using the simpletest example. I tried setting ssl to false as suggested by brentru and that didn't work either.

Traceback (most recent call last):
  File "code.py", line 148, in <module>
  File "adafruit_aws_iot.py", line 155, in connect
  File "adafruit_aws_iot.py", line 155, in connect
AWS_IOT_ERROR: ('Error connecting to AWS IoT: ', MMQTTException('Invalid broker address defined.', RuntimeError('ESP32 not responding',)))

**Comment by virgilvox** [comment]
I enabled logs and it stops right after it tries to connect to mqtt. Tried secure and insecure. (is_ssl true/false)

12112.4: DEBUG - Attempting to establish insecure MQTT connection...
Traceback (most recent call last):
  File "code.py", line 150, in <module>
  File "adafruit_aws_iot.py", line 155, in connect
  File "adafruit_aws_iot.py", line 155, in connect
AWS_IOT_ERROR: ('Error connecting to AWS IoT: ', MMQTTException('Invalid broker address defined.', RuntimeError('ESP32 not responding',)))

**Comment by virgilvox** [comment]
@brentru Have you had a chance to give this a try recently?

**Comment by brentru** [comment]
Hi Moheeb, I haven't had a moment to look into this yet. Does it still occur if you use the previous release of Adafruit_CircuitPython_MiniMQTT ?

**Comment by virgilvox** [comment]
So its still an issue. I just checked the nina firmware and dont find the the AWS root cert in there for AWS IoT https://github.com/adafruit/nina-fw/blob/master/data/roots.pem

**Comment by virgilvox** [comment]
Made a pull request there to add. https://github.com/adafruit/nina-fw/pull/21

**Comment by virgilvox** [comment]
Just tested with the changes I made in that pull request, it works now. Closing this issue. Lmk when you get a chance to look at the PR / make a release <3

**Comment by darianbjohnson** [comment]
@virgilvox - I'm getting this error (using v 1.6.1 of nini_fw); is there a chance that a new root cert for AWS needs to be added?

**Comment by brentru** [comment]
@darianbjohnson Hi Darian. IIRC @virgilvox is not currently affiliated with AWS IoT. 

Could you ask Amazon AWS IoT for a new root certificate? I will be happy to add it to nina-fw.

**Comment by darianbjohnson** [comment]
@brentru I'm not 100% sure it's a root cert issue. The code connects using Arduino.... so in theory that means the issue is not related to the cert. I'll do more research and come back with something more definitive....

**Comment by brentru** [comment]
@darianbjohnson  Could you copy and paste the Arduino code you're using?

**Comment by speccy88** [comment]
Most of the time, I found out that if the broker is working and the address is fine and I have this error, it is because I needed to set "is_ssl" to False
see the doc : https://circuitpython.readthedocs.io/projects/minimqtt/en/latest/api.html#adafruit_minimqtt.adafruit_minimqtt.MQTT
