### ISSUE TITLE
Support for ESP32 Direct Boards

### ISSUE THREAD

**Issue by alanzhaonys** [adafruit/Adafruit_CircuitPython_AWS_IOT#21]
Any plan to support the ESP32 direct boards, for example the [ESP-32 S3 TFT Reverse](https://www.adafruit.com/product/5691) board.

See discussion here:
https://forums.adafruit.com/viewtopic.php?p=966126#p966126

**Comment by brentru** [comment]
@alanzhaonys Nothing is officially planned for this library in that direction afaik. We accept pull requests from the community, though.

**Comment by Neradoc** [comment]
I don't have a AWS account setup to test, but as far as I can tell this library is totally agnostic to the underlying network interface. I takes an MQTT instance, which is compatible with native wifi. If I'm correct, an example could be written by replacing the ESP32SPI and MQTT setup with that from the MQTT native wifi example.

https://github.com/adafruit/Adafruit_CircuitPython_AWS_IOT/blob/main/examples/aws_iot_simpletest.py
+
https://github.com/adafruit/Adafruit_CircuitPython_MiniMQTT/blob/main/examples/native_networking/minimqtt_adafruitio_native_networking.py

**Comment by justmobilize** [comment]
@brentru and @dhalbert since this relies on MiniMQTT, which fully supports any interface, I think this can be closed?
